baseURL = "http://localhost:1313/post"
languageCode = "en"
title = "Dusty Turner"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true

relativeurls = true

ignoreFiles = [ "^Thumbs\\.db$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$" ]

# Disqus Username
disqusShortname = "dusty-turner"

# Google Analytics UA number
googleAnalytics = "UA-109926409-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you likes to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
name = "Home"
weight = 10
identifier = "home"
url = "/post"

[[menu.main]]
name = "Github"
weight = 20
identifier = "works"
url = "https://github.com/dusty-turner"

[[menu.main]]
name = "CV"
weight = 50
identifier = "cv"
url = "/CV.pdf"



# Add your own params here
[params]
author = "Dusty Turner"
avatar = "/img/dusty.png"
seotitle = "Data Science: Lightly Edited"
#  seotitle = "Dusty Turner's R Data Science Blog"
subtitle = "~Data Science: Lightly Edited~"
#  subtitle = "~Becoming a Better Data Scientist Everyday~"
description = "Sharing my experiences learning Data Science through R"
paginate = 10
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"

# Choose your social networks
email = "dusty.s.turner@gmail.com"
github = "dusty-turner"
twitter = "dtdusty"
linkedin = "dusty-turner-34a148112"
# weibo = "weibo_username"
# wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
facebook = "dusty.turner"
# google = "googlplus_id_number"
# instagram = "instagram_username"
# youtube = "youtube_username"
# vimeo = "vimeo_username"
# medium = "medium_username"
# quora = "quora_username"
# pinterest = "pinterest_username"
# dribbble = "dribbble_username"
# behance = "behance_username"
# jsfiddle = "jsfiddle_username"
# codepen = "codepen_username"
# zhihu = "zhihu_username"
# douban = "douban_username"
# bilibili = "bilibili_id_number"

# Google Webmaster
# https://www.google.com/webmasters/
googleSiteVerification = "-jH0wqxQCDh6JrcCbL9tuGso_EV4u1BRT93XjGqNsfo"

# Bing Webmaster
# https://www.bing.com/toolbox/webmaster/
msValidate = "84DDAAE7986A2E9D73062694A69D33A9"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
