---
title: 2018 Joint Statistical Meeting Presentation
author: Dusty Turner
date: '2018-08-15'
slug: 2018-joint-statistical-meeting-presentation
categories:
  - army math
  - beatnavy
  - datascience
  - model building
tags:
  - army math
  - beatnavy
  - datascience
  - model building
---

I was honored to present some collaborative work between my friend [Jim Pleuss](https://www.usma.edu/math/_layouts/wpFacultyBios/DisplayBio.aspx?ID=f78a38a8-eba1-4241-b993-fb91fa075455&List=1ebd54dc-d44d-4834-8add-2da90afb21f5) and I at the [2018 Joint Statistical Meetings](http://ww2.amstat.org/meetings/jsm/2018/)

The question we attemped to answer is: Do students who are grouped with others of like ability perform better?

Short answer: Not really.

Full details are included in my presentations repository on my Github [here](https://github.com/dusty-turner/Presentations/blob/master/JSM%20Presentation%20Turner.pptx)

The poster is located [here](https://github.com/dusty-turner/Presentations/blob/master/JSM%20Poster%20Turner.ppt)

Oh, and Jim and I went for a little "R" run as well in Vancouver.

<center>
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Went for a good run in Vancouv-R. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/JSM2018?src=hash&amp;ref_src=twsrc%5Etfw">#JSM2018</a> <a href="https://twitter.com/MeetVancouver?ref_src=twsrc%5Etfw">@MeetVancouver</a> <a href="https://t.co/lNUikd481w">pic.twitter.com/lNUikd481w</a></p>&mdash; Dusty Turner (@DTDusty) <a href="https://twitter.com/DTDusty/status/1024448564842229760?ref_src=twsrc%5Etfw">August 1, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</center>

And I do have to a shoutout to the Vancouver Tourism folks at [MeetVancouver](https://twitter.com/MeetVancouver) .  Had a great positive interaction with them on Twitter and left with some nice gifts!

<center>
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Thanks for the great hospitality <a href="https://twitter.com/MeetVancouver?ref_src=twsrc%5Etfw">@MeetVancouver</a>!  <a href="https://twitter.com/hashtag/bestcityincanada?src=hash&amp;ref_src=twsrc%5Etfw">#bestcityincanada</a> <a href="https://t.co/GrNvoC5NgW">pic.twitter.com/GrNvoC5NgW</a></p>&mdash; Dusty Turner (@DTDusty) <a href="https://twitter.com/DTDusty/status/1024439503446978561?ref_src=twsrc%5Etfw">July 31, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</center>